"""empty message

Revision ID: 525645531795
Revises: 82028415bcf8
Create Date: 2025-10-07 23:04:49.032092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525645531795'
down_revision = '82028415bcf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
