"""empty message

Revision ID: 82028415bcf8
Revises: 0763d677d453
Create Date: 2025-09-01 04:09:51.864444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82028415bcf8'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_email_key', ['email'])

    # ### end Alembic commands ###
